In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [33]:
#plano concave

r1 = np.array([3.1, 4.2, 2.1, 5.3, 6.6])/2

r2 = np.array([3.7, 4.8, 3.5, 5.9, 7.2])/2

z = np.array([20, 30, 15, 40, 50])

y = np.array([15, 25, 10, 35, 45])

print(r1)
print(r2)

f = r2*(z - y)/(r2-r1) - y

print(f)

delta = 0.1

err_f = f*delta*(2/(2*r2 + r1 + z + y))
print(err_f.mean())

[1.55 2.1  1.05 2.65 3.3 ]
[1.85 2.4  1.75 2.95 3.6 ]
[15.83333333 15.          2.5        14.16666667 15.        ]
0.04128170735474177


In [80]:
# convex mirror

r1 = np.array([1.75, 2.05, 2.4, 2.65, 2.75])

r2 = np.array([2.05, 2.4, 2.65, 2.75, 3])

y = np.array([10, 15, 20, 25, 30])

z = np.array([15, 20, 25, 30, 35])

r1 = r1[::2]

r2 = r2[::2]

y = y[::2]

z = z[::2]

f = r2*(z - y)/(r2-r1) - y

err_f = f*delta*(2/(2*r2 + r1 + z + y))
print(err_f.mean())

0.12108839766868457


In [81]:
#Concave mirror

f = [34.5, 32, 34.5, 34.1, 34.5]

np.mean(f)

33.92

In [91]:
#convex lens

o = 15

l = np.array([33.5, 40, 35, 45, 50])

i = np.array([104.8, 77.5, 92.8, 75.5, 76.9])

u = l - o

v = i - l

f = np.round(u*v/(u+v), 1)


print(u)

print(v)
print(f)

print(f.mean())

err_f = f*delta*2*(1/u + 1/v)

print(err_f.mean())

[18.5 25.  20.  30.  35. ]
[71.3 37.5 57.8 30.5 26.9]
[14.7 15.  14.9 15.1 15.2]
14.98
0.2000523178652384


In [123]:
o = np.array([45, 30, 30, 45, 30])

l = np.array([76.8, 80, 82, 72, 85])

i = np.array([105.5, 100.6, 97.5, 128.4, 96.5])

u = l - o

v = i - l

f = np.round((u*v)/(u+v), 1)

print(u)

print(v)
print(f)

print(f.mean())

err_f = f*delta*2*(1/u + 1/v)

print(err_f.mean())

[31.8 50.  52.  27.  55. ]
[28.7 20.6 15.5 56.4 11.5]
[15.1 14.6 11.9 18.3  9.5]
13.88
0.199974448680706


In [128]:
f = np.array([30.5, 30.1, 30.4, 29.9, 30.3])/2

err_f = f*delta*4/f

err_f.mean()

0.4

In [132]:
s = np.array([92.2, 104.2,  87.5, 90.7, 93 ])
m = np.array([63.4, 74.3, 58.8, 61.5, 65])

f = (s - m)/2

err_f = f*delta*(1/s + 1/m)
print(err_f.mean())

0.038006708365755905
