In [2]:
pwd

'/home/darkwake/Desktop'

In [3]:
import numpy as np

In [4]:
rad = np.array([15.9, 28.3, 34.7, 42.5, 46.2])/2
xn2 = rad**2 - rad[0]**2

In [5]:
xn2

array([  0.    , 137.02  , 237.82  , 388.36  , 470.4075])

In [15]:
rad

array([ 7.95, 14.15, 17.35, 21.25, 23.1 ])

In [6]:
rad**2

array([ 63.2025, 200.2225, 301.0225, 451.5625, 533.61  ])

In [16]:
xn2

array([  0.    , 137.02  , 237.82  , 388.36  , 470.4075])

In [13]:
t = [1000*i * (0.905**2) * (650 * 1e-9)/(xn2[i] * 1e-6) for i in range(1,len(xn2))]

In [14]:
t

[3.8853178368121446, 4.477051972079724, 4.112418245957359, 4.526851718988324]

In [17]:
np.mean(t)

4.250409943459388

In [25]:
(1/(xn2[1:])**0.5).mean()

0.061781194567482434

In [30]:
3.53 * 0.2*((1/90.5) + (1/(xn2[1:])**0.5).mean())

0.05141862833701828

In [28]:
1.5/4.25

0.35294117647058826